# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Publish
      run: dotnet publish -c Release
    - name: stop service
      uses: Sithi5/remote-ssh-commands-action@1.1.2
      with:
        # ssh user
        SSH_USER: ${{ secrets.DROPLET_USER }}
        # ssh private key
        SSH_PRIVATE_KEY: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        # ssh host
        SSH_HOST: ${{ secrets.DROPLET_HOST }}
        # command to execute in the remote server.
        SSH_REMOTE_COMMANDS: systemctl stop epgp-api.service
    - name: Place published files onto droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        source: "bin/Release/net7.0/publish"
        target: "${{ secrets.DROPLET_TARGET_DIR }}"
    - name: start service
      uses: Sithi5/remote-ssh-commands-action@1.1.2
      with:
        # ssh user
        SSH_USER: ${{ secrets.DROPLET_USER }}
        # ssh private key
        SSH_PRIVATE_KEY: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        # ssh host
        SSH_HOST: ${{ secrets.DROPLET_HOST }}
        # command to execute in the remote server.
        SSH_REMOTE_COMMANDS: systemctl start epgp-api.service
