# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Publish
      run: dotnet publish -c Release        
    - name: stop service
      uses: fifsky/ssh-action@v0.0.6
      with:
        # Command to execute on the remote server.
        command: systemctl stop epgp-api.service
        # Hostname or IP address of the server.
        host: ${{ secrets.DROPLET_HOST }}
        # Username for authentication.
        user: ${{ secrets.DROPLET_USER }}
        # Port number of the server.
        port: 22
        # String that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
        key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}        
    - name: Place published files onto droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        source: "bin/Release/net7.0/publish"
        target: "${{ secrets.DROPLET_TARGET_DIR }}"
    - name: start service
      uses: fifsky/ssh-action@v0.0.6
      with:
        # Command to execute on the remote server.
        command: systemctl start epgp-api.service
        # Hostname or IP address of the server.
        host: ${{ secrets.DROPLET_HOST }}
        # Username for authentication.
        user: ${{ secrets.DROPLET_USER }}
        # Port number of the server.
        port: 22
        # String that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
        key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}  
