# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore -r linux-x64
    - name: Build
      run: dotnet build --configuration Release --no-restore -r linux-x64
    - name: Publish
      run: dotnet publish --no-build --no-restore -c Release -r linux-x64 /p:PublishSingleFile=true
    - name: Place published single file onto droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        source: "bin/Release/netcoreapp3.1/linux-x64/publish"
        target: "${{ secrets.DROPLET_TARGET_DIR }}"

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        script: sudo supervisorctl start joy
