name: Deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: stop service
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: systemctl stop epgp-api.service
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        privateKey: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
    - name: start service
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: systemctl start epgp-api.service
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        privateKey: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
