name: Restart Service

# Controls when the workflow will run
on:
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
 workflow_run:
  workflows: ['[TEST] Build and deploy']
  types:
   - completed
jobs:
 build:
  runs-on: self-hosted
  steps:
   - name: stop service
     run: sudo systemctl stop test.epgp-api.service
   - name: start service
     run: sudo systemctl start test.epgp-api.service
