name: Restart Service

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:

  build:

    runs-on: self-hosted
    steps:
    - name: stop service
      run: systemctl stop epgp-api.service
    - name: start service
      run: systemctl start epgp-api.service
